### ISSUE TITLE
relationships.data not populated

### ISSUE THREAD

**Issue by collinpeters** [katharsis-project/katharsis-core#117]
I have the following in a `User` class

    @JsonApiToMany
    @JsonApiIncludeByDefault
    private List<Group> groups;

The `groups` attribute is populated, but I do not get the `relationships.data` in the response. I get

	{
		"data": {
			"type": "users",
			"id": "aGgB1",
			"attributes": {
				"firstName": "Admin",
				"lastName": "Foo",
				<snip>
			},
			"relationships": {
				"groups": {
					"links": {
						"self": "/users/aGgB1/relationships/groups",
						"related": "/users/aGgB1/groups"
					}
				}
			},
			"links": {
				"self": "/users/aGgB1"
			}
		},
		"included": [
			{
				"type": "groups",
				"id": "V0KYQ",
				"attributes": {
					"name": "Test 1",
					"id": "V0KYQ"
				},
				"relationships": {},
				"links": {
					"self": "/groups/V0KYQ"
				}
			},
			{
				"type": "groups",
				"id": "NQJwD",
				"attributes": {
					"name": "Test 2",
					"id": "NQJwD"
				},
				"relationships": {},
				"links": {
					"self": "/groups/NQJwD"
				}
			}
		]
	}

I am not sure why it is not populated as I am expecting it to be.

**Comment by meshuga** [comment]
Because the ToMany relation can link to many resources, like hundreds or so, there is a lazy-fetching mechanism for reducing the amount of data to be sent. 

If you want to have `data` field filled with relationships, you should have `@JsonApiToMany(lazy = false)` annotation. It isn't in the documentation, but I'll update it this weekend.

**Comment by collinpeters** [comment]
Thanks. CC @zachncst
