### ISSUE TITLE
How to handle security (authorizied resource access)?

### ISSUE THREAD

**Issue by ieugen** [katharsis-project/katharsis-core#151]
Hi, 

Do you have a strategy to handle cases where you should be allowed to access (delete) a resource only if you have a certain role or permission? 

Looking on how the API is defined right now the only way you could make this happen is via some kind of introspection (Annotations).  Whule this is ok in some cases, I personally try to avoid them as they tend to be a sort of magic thing. 

I'm asking because I'm working on integrating katharsis with vertx.io for a project. I'm stil early in the implementation but I can't seem to figure a good way to do this.

**Comment by meshuga** [comment]
The simplest way is to implement it in your repository. But there are other ways which depend on what other frameworks you integrate Vert.x with:
- You could write your own adapter to Vert.x and implement own `RepositoryParameterProvider` like here: https://github.com/katharsis-project/katharsis-rs/blob/development/src/main/java/io/katharsis/rs/JaxRsParameterProvider.java to pass authN+Z information to the repositories
- You could use Vert.x Spring integration - https://github.com/vert-x3/vertx-examples/tree/master/spring-examples and implement security interceptors, write some filter to do that or do it in your repositories
- You could use Jersey integration, write some filter to do that or use `SecurityContext` to check for an appropriate role in your repositories: https://github.com/englishtown/vertx-jersey (for me the best option in terms of performance vs. code maintainability)

But as stated in https://github.com/katharsis-project/katharsis-core/issues/130, Katharsis is synchronous, so all of the calls to the Katharsis will block the event loop unless you implement own integration and make use of https://github.com/vert-x3/vertx-sync.

I've been thinking about making the library async, but I encountered a problem what kind of async orchestration to use. Java `Future` option sucks, because sometimes it's blocking and personally I would use RxJava, but it would raise the problems of interoperability when someone don't use async libraries at all.

**Comment by ieugen** [comment]
Thank you for the options. I have some ideas that I wish to try out. I'll come back with info regarding the process. I wish to stay away from spring. It's ok, but I try to avoid it when I can. It adds a lot of magic and while annotations seem a good idea, they tend to be overused and abused and the results are not very pretty. 

Regarding Async, there is a difference between API and implementation. You could make an async API by having methods with callbacks instead of returning the thing directly.  Maybe it's not pretty but it makes things possible. 

Building a good API is no small task and it takes time.

**Comment by meshuga** [comment]
Callbacks are an option, but the amount of additional code that needs to be made is pretty big and at the end of the day I'll be left with more synchronization issues than with other problems.
