### ISSUE TITLE
Support for @PermitAll, SecurityContext and related functionality

### ISSUE THREAD

**Issue by joewildish** [katharsis-project/katharsis-core#194]
I am using Dropwizard (0.9.1) with Katharsis (2.1.1).

Let's say I configure security on a (non-Katharsis) resource by using an AuthDynamicFeature and some annotations, like so:

```java
/* Main.java */
environment.jersey().register(
  new AuthDynamicFeature(
    new OAuthCredentialAuthFilter.Builder<UserAccount>()
      .setAuthenticator(new UserAuthenticator())
      .setAuthorizer(new UserAuthorizer())
      .setPrefix("SomePrefix")
      .buildAuthFilter())
);
environment.jersey().register(RolesAllowedDynamicFeature.class);
environment.jersey().register(new AuthValueFactoryProvider.Binder<>(UserAccount.class));

/* PingResource.java */
@GET
@PermitAll
public Pong get(@Context SecurityContext securityContext) {
  UserAccount principal = (UserAccount) securityContext.getUserPrincipal();
  return new Pong(principal.getName());
}
```

I was expecting to be able to do the same on a ResourceRepository:

```java
@PermitAll
@JsonApiFindAll
public Iterable<SomeResource> findAll(QueryParams queryParams, @Context SecurityContext security) {
  /* ... */
}
```

However it would seem that the Authentication mechanism is not being called when the GET request is made. Can you advise if what I'm trying to do is possible please?

Thanks.
-Joe

**Comment by meshuga** [comment]
Current Dropwizard implementation uses JAX-RS DynamicFeature - https://github.com/dropwizard/dropwizard/blob/master/dropwizard-auth/src/main/java/io/dropwizard/auth/AuthDynamicFeature.java which is unavailable since katharsis-rs doesn't use JAX-RS matcher to resolve the repository method to call.

You should implement it by yourself and I think the easiest way is by adding a filter which will be run before Katharsis request processing.

**Comment by joewildish** [comment]
I've just had a quick look at the code and I don't think it's as simple as that unfortunately.

From what I can see the ```KatharsisFeature``` registers a ```@PreMatching``` filter that essentially handles the routing of a request to a method. My regular filter (ie. "post-matching") doesn't therefore get called. I really need it to be a regular filter as I need the ```ResourceInfo``` information (or equivalent) to make a decision about if a request requires authentication and/or authorisation.

I'll take a further look later today and see if there is an approach that I can get working.

**Comment by meshuga** [comment]
Well, there is a way, but pretty hard. You could write a code that will grab all of the resources and for each of them create a set of resources which will allow JAX-RS matching to be used. It might work with Jersey - https://jersey.java.net/documentation/latest/resource-builder.html

But how to make Jersey read annotations from repository? I don't know :wink:

**Comment by joewildish** [comment]
Yes I realised that could be an approach but agree it is quite involved.

Is there another way you think may be appropriate to implement authentication and/or authentication in my scenario? I imagine using a dropwizard+katharsis combination must be quite common, as must be secured services, but I can't see how this is do-able without being able to attach custom filters in the same way you can with JAX-RS.

**Comment by ctapaswi** [comment]
Guys I am facing the same issue now. I have integrated Katharsis for adding JsonAPI compliance for our APIs. But I am not sure how can I do following

- Something like RolesAllowed annotation so I can abort response before it ever reaches repository method when user is not in the role required by method
- Any other custom annotation that I can add to repository method so in post matching phase, my filter can get called and I can use this annotation to do any checks before Katharsis dispatcher executes the repository method.
Any suggestions?

**Comment by keithdmoore** [comment]
If you are using Spring,  you can use Spring Security annotations.  This assuming you have added the RoleAuthorities as part of your authentication process.  https://docs.spring.io/spring-security/site/docs/current/reference/html/el-access.html.

**Comment by ctapaswi** [comment]
Thanks, but I am using Jersey on tomcat. I have enabled RolesAllowedDynamicFeature but thats not going to work because Katharsis filter just dispatches the request to repostory method.

For doing any filtering based on custom or in built annotations, we need to have the ability to add post matching filters before resource method is called and that does not seem to be possible.

Also @meshuga even with JaxrsParameter provider or any custom parameter provider, I don't know how I get access to "provided" context parameters in my repository method.

public Iterable<Member> findAll(QueryParams queryParams)

So here how would I get access to provided params, security context or anything custom?

**Comment by meshuga** [comment]
You can do sth like:
```
@JsonApiFindAll
public Iterable findAll(QueryParams queryParams, SecurityContext securityContext)
```
Note that it's supported only in annotation based repositories.

**Comment by ctapaswi** [comment]
Thanks for the quick response. let me give that a shot.

**Comment by ctapaswi** [comment]
@meshuga 

#1 I changed my repo to be annotation based but SecutiyContext is coming in as null, even though in a separate pre-matching filter I am setting it as follows

Pre Matching filter
request.setSecurityContext(new RequestSecurityContext(new Member(), false));

Annotation based repo
@JsonApiResourceRepository(value = Member.class)
public class MemberResourceRepository {

    @JsonApiFindOne
    public Member findOne(Long aLong, QueryParams queryParams, SecurityContext securityContext) {

This still does not give me security context?

#2 Is there any way I can inject my own filter in post matching phase? Because really we do not want to duplicate authorization code in every resource API that is being called.

**Comment by meshuga** [comment]
ad. 1 Are you sure it's fired before Katharsis? Security context is just taken from the request by this class: https://github.com/katharsis-project/katharsis-rs/blob/development/src/main/java/io/katharsis/rs/parameterProvider/provider/SecurityContextProvider.java#L12

ad. 2 I think it should be possible using `@javax.annotation.Priority` annotation. It's the last one executed type of filter - https://jersey.java.net/documentation/latest/filters-and-interceptors.html#d0e9927 so even Pre-matching ones will apply.

**Comment by ctapaswi** [comment]
#1 Yes i know that because I have break point there and I am populating request context with my own security context.

#2 So my pre-matching filters are getting called but, post matching is not getting called, with any value for priority. I want a apost matching filter because I need to know which method Katharsis selected so I can get annotations on that method and then perform any logic based on those annotations.

**Comment by ctapaswi** [comment]
Any thoughts @meshuga?

**Comment by meshuga** [comment]
There's no way it can be done. Just after Katharsis matches the controller, the request is executed.

**Comment by ctapaswi** [comment]
Thanks. But then does that mean that every repository method has to have a duplicate code which validates for incoming request, like Authorization etc?

**Comment by ctapaswi** [comment]
@meshuga one more question, if in the same app I need to support has following paths

/api/v1/someRoot/path1/
/api/v1/someRoot/path2/
/api/v1/someRoot/path2/path3

How do I created resources and resource repositories that will correctly map these paths?

**Comment by ctapaswi** [comment]
@meshuga, if I need to include a complex object inside my resource without any relation katharsis is not serializing it. For example

@JsonApiResource(type= "tasks")
public class Foo {
    @JsonApiId
    private String id;
    private String simpleStr;

    @JsonProperty("someProperty")
    private ComplexObject complexObject = null;

Now when I call Foo resource API its not serializing ComplexObject but its serializing simpleStr. Am I missing something here?

**Comment by cparker92** [comment]
@ctapaswi I think you could solve your authentication problem by implementing a [RequestContextParameterProvider](https://github.com/katharsis-project/katharsis-rs/blob/development/src/main/java/io/katharsis/rs/parameterProvider/provider/RequestContextParameterProvider.java). You could add an extra parameter to your repo methods with any annotations you want and then in the provide method you can analyze the annotation values and use the request context to authorize the client.

**Comment by ctapaswi** [comment]
Thanks @cparker92,  yeah this was suggested before, the problem is that means for every method we will have to call "filter" to authorize. With jersey filters I just write those and they are called by the framework before my resource API is invoked. This way by the time by resource API is called these things are taken care of.
