### ISSUE TITLE
@JsonApiId should be @Inherited

### ISSUE THREAD

**Issue by collinpeters** [katharsis-project/katharsis-core#197]
I have a base object on all my domain entities which provides a getter for the API ID
```
	@JsonApiId
	public String getHashId() {
             ...
	}
```

This no longer works with Katharsis 2.0. It did work with 1.x so I'm not sure if it was removed on purpose or what. It has caused my to have to override the method in all my entities
```
	@JsonApiId
	public String getHashId() {
		return super.getHashId();
	}
```

**Comment by meshuga** [comment]
`@Inherited` annotation never been placed on either `@JsonApiId` or any other Katharsis annotation. Annotation inheritance is made by hand using `ResourceInformationBuilder#build(Class<?>)` https://github.com/katharsis-project/katharsis-core/blob/f0b83dccbeecabca4d0f782e5da62a2ed86678be/src/main/java/io/katharsis/resource/information/ResourceInformationBuilder.java#L32-L32.
Could you show a gist with your configuration? Maybe the problem is somewhere else.

**Comment by collinpeters** [comment]
Hrm....  not sure where I went awry but it is now working. I think my mistake was that I had a private attribute `hashId` which had `@JsonIgnore` on it, then a getter with `@JsonApiId`. The JsonIgnore seemed to mess it up. In any case I must have removed it at some point as it is all working now.
