### ISSUE TITLE
Metrics and Documentation support

### ISSUE THREAD

**Issue by ashishgodani** [katharsis-project/katharsis-core#207]
I would like to know if there is a way to integrate Codehale and Swagger with Katharsis-Spring ? 
If yes, could you please provide me with some pointers/references ?

**Comment by meshuga** [comment]
For now there's no code that could help you doing that. Lately I found that Springfox documentation mentions jsonapi (http://springfox.github.io/springfox/docs/current/#goals) but it's a general goal rather than a real implementation. 
But, if you have some free time you could take a look at https://github.com/woonsan/swagger-katharsis and start to hack it :wink:
